language: php
php:
  - 7.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl openssh-client
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
    repo: rbas/kkkk
before_install:
  - openssl aes-256-cbc -K $encrypted_248b4e8cf39a_key -iv $encrypted_248b4e8cf39a_iv -in id_rsa.enc -out id_rsa -d
