language: php
php:
  - 7.0
#addons:
#  apt:
#    packages:
#      - openssl
#      - openssh-client
deploy:
  provider: script
  script: ls -alh 
#  skip_cleanup: true
  on:
    branch: master
    repo: rbas/kkkk
after_success:
  - chmod 600 ~/.ssh/id_rsa
before_install:
  - openssl aes-256-cbc -K $encrypted_248b4e8cf39a_key -iv $encrypted_248b4e8cf39a_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
