language: php
php:
  - 7.0
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    repo: rbas/kkkk
after_success:
  - chmod 600 id_rsa
  - mv id_rsa ~/.ssh/id_rsa
before_install:
  - openssl aes-256-cbc -K $encrypted_248b4e8cf39a_key -iv $encrypted_248b4e8cf39a_iv -in id_rsa.enc -out id_rsa -d
