language: php
php:
  - 7.0
script: "phpunit tests/"
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_248b4e8cf39a_key -iv $encrypted_248b4e8cf39a_iv -in id_rsa.enc -out id_rsa -d
